### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by sunesh** [att-comdev/treasuremap#10]
On page https://treasuremap.readthedocs.io/en/latest/deployment.html#component-overview
under 
Establishing build node environment
On the machine you wish to **sue** to generate deployment files, install required tooling:
should read
On the machine you wish to **use** to generate deployment files, install required tooling:

**Comment by gorshunovr** [comment]
Thank you, @sunesh .

**Comment by sunesh** [comment]
you're welcome ;-)
    On Thursday, June 21, 2018, 9:37:07 AM PDT, Roman Gorshunov <notifications@github.com> wrote:  
 
 
Thank you, @sunesh .
